#!/bin/bash

CPUTEMP=$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2`)).$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c3-4`))

echo "$CPUTEMP" >> cputmp.txt

#cat cputmp.txt
echo cpu temp
tail -n 1 cputmp.txt