#!/bin/bash

dpkg -s sysstat &> /dev/null

echo "sysstat"


    if ! dpkg -s sysstat &> /dev/null

        then
            echo "not installed"  
            sudo apt-get update
            sudo apt-get install sysstat

        else
            echo    "installed"
    fi

echo CPU USAGE ; mpstat