#!/bin/bash

sudo sh -c "echo none >/sys/class/leds/led0/trigger"

while true; do

DELAY=$(tail -1 ./logs/cpu_av.dat | awk '{print $2}')

sudo sh -c "echo 1 >/sys/class/leds/led0/brightness"

sleep "$DELAY"

sudo sh -c "echo 0 >/sys/class/leds/led0/brightness"

done









#sudo sh -c "echo heartbeat >/sys/class/leds/led0/trigger"

#echo mmc0 >/sys/class/leds/led0/trigger