#!/bin/bash

trap endseq INT

dpkg -s sysstat &> /dev/null

endseq() { 

echo -  -   -   -   -   -   - SAVING - -   -   -   -   -   -   -   -   

./cpu_temp

./gpu_temp

./cpu_freq

./mem_stat

./cpu_use
    
sleep 2

    echo -  -  -   -   -   -   -   - EXITING - -   -   -   -   -   -   -   -   

    exit 0
}

echo "sysstat"

    if ! dpkg -s sysstat &> /dev/null

        then
            echo "not installed"  
            sudo apt-get update
            sudo apt-get install sysstat

        else
            echo    "installed"
    fi

while true ; do

sleep 1

echo -  -   -   -   -   -   -   - RUNNING - -   -   -   -   -   -   -   -   

./cpu_temp

./gpu_temp

./cpu_freq

./mem_stat

./cpu_use


done