#!/bin/bash

#inform user 
printf "\nTo exit at any time type \"kill -USR1 $$\""

#trap signal, call close sequence
trap close USR1

#define close sequence
close() { 

(( SECINC++ ))

#plots cpu psercentages
gnuplot -e "plot \"./logs/cpuusr.dat\" using 2 title 'USER' with lines, \
\"./logs/cpusys.dat\" using 2 title 'SYSTEM' with lines, \
\"./logs/cpuidl.dat\" using 2 title 'IDLE' with lines; pause -1"

#plots cpu and gpu temp
gnuplot -e "plot \"./logs/cputmp.dat\" using 2 title 'CPUTEMP' with lines, \
\"./logs/gputemp.dat\" using 2 title 'GPUTEMP' with lines; pause -1"

#inform user
printf "\n-  -   -   -   -   -   -   - SAVING - -   -   -   -   -   -   -   -   "

#delay for user to readability
sleep 1

#get cpu temp, format data and save to log
CPUTEMP=$(awk '{print $1}' /sys/class/thermal/thermal_zone0/temp | cut -c1-2 ).$(awk '{print $1}' /sys/class/thermal/thermal_zone0/temp | cut -c3-4)

#save output to logfile
echo $SECINC "$CPUTEMP" >> ./logs/cputmp.dat

#get gpu temp, format data and save to log
GPUTMP=$((vcgencmd measure_temp) | cut -c6-9) 

#save output to logfile
echo $SECINC $GPUTMP >> ./logs/gputemp.dat

#get cpu freq, format data and save to log
CLOCKHZ=$((vcgencmd measure_clock arm) | cut -c15-25) 

#MHZ divisor
MHZDV=100000000 

#processing data to represent MHZ
CLKMHZ=$((CLOCKHZ / MHZDV)) 


#save output to logfile
echo $SECINC $CLKMHZ >> ./logs/cpufreq.dat

#get memory stats, format data and save to log
MSTAT=$(free -h | cut -c13-80 )


#format data
MSTAT=$(echo $MSTAT | sed -e "s/total used free shared buff\/cache available //g" | sed -e "s/Gi//g" | sed -e "s/Mi//g" |  sed -e "s/B//g" )

#save output to logfile
echo $SECINC $MSTAT  >> ./logs/mstat.dat

#get cpu use, format data and save to log
CPUUUSR=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$3}")

echo $SECINC $CPUUUSR >> ./logs/cpuusr.dat

CPUSYS=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$5}")

echo $SECINC $CPUSYS >> ./logs/cpusys.dat

CPUIDL=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$12}" | cut -c1-2)

CPUPCT=.$CPUIDL

#save output to logfile
echo $SECINC $CPUPCT >> ./logs/cpuidl.dat
    
#inform user
printf "\n-  -  -   -   -   -   -   - EXITING - -   -   -   -   -   -   -   -  "

#delay to make sequence change obvious    
sleep 1

#inform user
printf "\n-  -  -   -   -   -   -  - PROFILER CLOSED - -   -   -   -   -   -   -   -   "

#exit and set code
exit 0

}

#inform user
printf "\n-  -   - 	-	-   -	- STARTING PROFILER - -   -   -   -   -   -   -   -   "

#inform user
printf "\nsysstat is required"

#inform user
printf "\nchecking if installed"

#check if sysstat is installed
if ! dpkg -s sysstat &> /dev/null

#if not installed, update and install
then

#inform user
printf "\nnot installed - installing"  

#update os
sudo apt-get update

#install systat
sudo apt-get install sysstat

#inform user
printf "\installed - continuing"

#if installed continue without installing
else

#inform user
printf    "\ninstalled"

#finish installation confirmation sequence
fi

#inform user
printf "\n-  -  -   -   -   -   -  - PROFILER RUNNING - -   -   -   -   -   -   -   -"

SECINC=0

rm -r ./logs/*

#loop functions to collect metrics every one second
while true ; do

#increment seconds
(( SECINC++ ))

#delay timer
sleep .0000001

#get cpu temp, format data and save to log
CPUTEMP=$(awk '{print $1}' /sys/class/thermal/thermal_zone0/temp | cut -c1-2 ).$(awk '{print $1}' /sys/class/thermal/thermal_zone0/temp | cut -c3-4)

#save output to logfile
echo $SECINC "$CPUTEMP" >> ./logs/cputmp.dat

#get gpu temp, format data and save to log
GPUTMP=$((vcgencmd measure_temp) | cut -c6-9) 

#save output to logfile
echo $SECINC $GPUTMP >> ./logs/gputemp.dat

#get cpu freq, format data and save to log
CLOCKHZ=$((vcgencmd measure_clock arm) | cut -c15-25) 

#MHZ divisor
MHZDV=100000000 

#processing data to represent MHZ
CLKMHZ=$((CLOCKHZ / MHZDV)) 

#save output to logfile
echo $SECINC $CLKMHZ >> ./logs/cpufreq.dat

#get memory stats, format data and save to log
MSTAT=$(free -h | cut -c13-80)

#format data
MSTAT=$(echo $MSTAT | sed -e "s/total used free shared buff\/cache available //g" | sed -e "s/Gi//g" | sed -e "s/Mi//g" |  sed -e "s/B//g" )

#save output to logfile
echo $SECINC $MSTAT  >> ./logs/mstat.dat

#get cpu use, format data and save to log
CPUUUSR=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$3}")

echo $SECINC $CPUUUSR >> ./logs/cpuusr.dat

CPUSYS=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$5}")

echo $SECINC $CPUSYS >> ./logs/cpusys.dat

CPUIDL=$(mpstat | awk 'FNR == 4 {print}' | awk "{ print \$12}" | cut -c1-2)

CPUPCT=.$CPUIDL

#save output to logfile
echo $SECINC $CPUPCT >> ./logs/cpuidl.dat

#loop complete
done
