#!/bin/bash

#sudo apt install sysstat

profiler_run=10

while [[ profiler_run -ge 0  ]] ; do  

sleep 1

cputemp=$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2`)).$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c3-5`))

echo CPU TEMP IS $cputemp

echo GPU FREQ IS ; 

sudo vcgencmd get_config int |

egrep "(gpu)_freq"
 
echo MEMORY STATS ARE ; free

echo CPU USAGE ; mpstat

((profiler_run--)) 

done