#!/bin/bash

#try block 
function try()
{
    echo $$
    [[ $- = *e* ]]; ERROR_OPT=$?
    set +e
}

#thow exit code
function throw()
{
    exit "$1"
}

#catch function
function catch()
{
    export exception_code=$?
    (( ERROR_OPT )) && set +e
    return $exception_code
}
