#!/bin/bash

gnuplot -e "set title \"CPU UTILIZATION\"; set ylabel \"PERCENTAGE % (x100)\"; set xlabel \"SECONDS\"; 
plot \"./logs/cpuusr.dat\" using 2 title 'USER' with linespoints, \
\"./logs/cpusys.dat\" using 2 title 'SYSTEM' with linespoints, \
\"./logs/cpuidl.dat\" using 2 title 'IDLE' with linespoints; pause -1; set term png size 
700,700; set output \"./graph_images/CPU_UTIL.png\"; replot;"